"""Database models matching the portfolio backend schema."""

from dataclasses import dataclass
from datetime import date, datetime
from typing import Optional
from uuid import UUID


@dataclass
class UserData:
    """User data matching the users table schema."""

    email: str
    name: str
    bio: str
    password_hash: str = ""  # Empty placeholder for LinkedIn imports
    avatar_url: Optional[str] = None
    id: Optional[UUID] = None  # Generated by database
    created_at: Optional[datetime] = None  # Generated by database
    updated_at: Optional[datetime] = None  # Generated by database


@dataclass
class ProjectData:
    """Project data matching the projects table schema."""

    slug: str
    title: str
    description: str
    long_description: Optional[str] = None
    image_url: Optional[str] = None
    live_url: Optional[str] = None
    github_url: Optional[str] = None
    featured: bool = False
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    id: Optional[UUID] = None  # Generated by database
    technologies: list[str] = None  # Skills/technologies to link

    def __post_init__(self):
        """Initialize empty list for technologies if None."""
        if self.technologies is None:
            self.technologies = []


@dataclass
class ExperienceData:
    """Work experience data matching the work_experiences table schema."""

    user_id: UUID
    company: str
    position: str
    location: Optional[str] = None
    description: Optional[str] = None
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    is_current: bool = False
    id: Optional[UUID] = None


@dataclass
class EducationData:
    """Education data matching the educations table schema."""

    user_id: UUID
    school: str
    degree: Optional[str] = None
    field_of_study: Optional[str] = None
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    description: Optional[str] = None
    grade: Optional[str] = None
    id: Optional[UUID] = None


@dataclass
class CertificationData:
    """Certification data matching the certifications table schema."""

    user_id: UUID
    name: str
    issuer: str
    url: Optional[str] = None
    issue_date: Optional[date] = None
    expiration_date: Optional[date] = None
    credential_id: Optional[str] = None
    id: Optional[UUID] = None


@dataclass
class UserSkillData:
    """User skill data matching the user_skills table schema."""

    user_id: UUID
    name: str
    category: Optional[str] = None
    proficiency_level: Optional[int] = None
    id: Optional[UUID] = None
