"""Database models matching the portfolio backend schema."""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional
from uuid import UUID


@dataclass
class UserData:
    """User data matching the users table schema."""

    email: str
    name: str
    bio: str
    password_hash: str = ""  # Empty placeholder for LinkedIn imports
    avatar_url: Optional[str] = None
    id: Optional[UUID] = None  # Generated by database
    created_at: Optional[datetime] = None  # Generated by database
    updated_at: Optional[datetime] = None  # Generated by database


@dataclass
class ProjectData:
    """Project data matching the projects table schema."""

    slug: str
    title: str
    description: str
    long_description: Optional[str] = None
    image_url: Optional[str] = None
    live_url: Optional[str] = None
    github_url: Optional[str] = None
    featured: bool = False
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    id: Optional[UUID] = None  # Generated by database
    technologies: list[str] = None  # Skills/technologies to link

    def __post_init__(self):
        """Initialize empty list for technologies if None."""
        if self.technologies is None:
            self.technologies = []
